version: '3'

services:
  database:
    image: mysql:8.0
    container_name: orderservice
    restart: always
    env_file:
      - ./.env
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
    volumes:
      - ./database:/var/lib/mysql
    ports:
      - "3306:3306"