version: '3'

services:
  orderservice_db:
    image: mysql:8.0
    container_name: orderservice_db
    restart: always
    env_file:
      - ./.env
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
    volumes:
      - ./../../var/database:/var/lib/mysql

  orderservice:
    container_name: orderservice
    build:
      context: ../
      dockerfile: docker/Dockerfile
    env_file:
      - ./.env
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    depends_on:
      - orderservice_db